name: Build and Package

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Compile and Package (Linux)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Set environment variable for Node.js 24
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: /node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm install

      - name: Install required packages for deb and rpm
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y dpkg-dev fakeroot build-essential rpm rpm-build

      - name: Compile SCSS and TypeScript
        run: npm run build

      - name: Build packages
        run: npm run make -- --arch=${{ matrix.architecture }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dump-verifier-linux-${{ matrix.architecture }}
          path: out/make

  build-macos:
    name: Compile and Package (macOS)
    runs-on: macos-latest

    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Set environment variable for Node.js 24
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: /node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm install

      - name: Compile SCSS and TypeScript
        run: npm run build

      - name: Build packages
        run: npm run make -- --arch=${{ matrix.architecture }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dump-verifier-macos-${{ matrix.architecture }}
          path: out/make

  build-windows:
    name: Compile and Package (Windows)
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Set environment variable for Node.js 24
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: /node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm install

      - name: Compile SCSS and TypeScript
        run: npm run build

      - name: Build packages
        run: npm run make -- --arch=${{ matrix.architecture }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dump-verifier-windows-${{ matrix.architecture }}
          path: out/make

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Get version from package.json
        id: get_version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_ENV

      - name: Extract changelog for release
        id: extract_changelog
        run: |
          version=$(node -p "require('./package.json').version")
          changelog=$(awk "/# v$version/,/^$/" changelog.md | sed '1d;$d')
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.version }}
          release_name: Release v${{ env.version }}
          body: ${{ env.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/make/dump-verifier-linux-*
          asset_name: dump-verifier-linux-${{ env.version }}.zip
          asset_content_type: application/zip

      - name: Upload macOS Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/make/dump-verifier-macos-*
          asset_name: dump-verifier-macos-${{ env.version }}.zip
          asset_content_type: application/zip

      - name: Upload Windows Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/make/dump-verifier-windows-*
          asset_name: dump-verifier-windows-${{ env.version }}.zip
          asset_content_type: application/zip
