name: ESlint & Prettier
run-name: Run ESLint and Prettier on modified files

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - 'src/**'
      - 'dist/html/**'
      - 'esbuild.config.ts'
      - 'eslint.config.ts'
      - 'forge.config.ts'
      - 'tsconfig.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  eslint-prettier:
    name: Run ESLint and Prettier on modified files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: /node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm install
        continue-on-error: true

      - name: Clear npm cache (if install fails)
        if: failure()
        run: npm cache clean --force

      - name: Run Prettier on modified files
        run: npx prettier --check .

      - name: Run ESLint on modified files
        run: npx eslint src/ts/*.ts
