name: ESlint
run-name: Run ESLint on modified files

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - '.github/workflows/eslint.yml'
      - 'src/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    name: Run ESLint on modified files
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable for Node.js 24
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      - name: Checkout only relevant files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/ts/
            esbuild.config.ts
            eslint.config.ts
            forge.config.ts
            tsconfig.json

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: /node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install ESLint
        run: |
          npm pkg delete scripts.prepare
          npm install

      - name: Run ESLint on modified files
        run: |

          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E '\.ts$' | grep -E '^(src/ts/|esbuild.config.ts|eslint.config.ts|forge.config.ts|tsconfig.json)')

          if [ -z "$FILES" ]; then
            echo "No TypeScript files modified. Skipping ESLint."
            exit 0
          fi

          echo "Running ESLint on modified files:"
          echo "$FILES"

          npx eslint $FILES
