name: Version Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - '.github/workflows/version.yml'
      - 'src/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-version:
    name: Check Version Number
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            package.json

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Get current version from package.json
        id: get_current_version
        run: |
          current_version=$(node -p "require('./package.json').version")
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Get latest release version
        id: get_latest_version
        run: |
          latest_version=$(gh release view --json tagName -q '.tagName' || echo "0.0.0")
          echo "latest_version=${latest_version#v}" >> $GITHUB_ENV

      - name: Compare versions
        id: compare_versions
        run: |
          if [ "$(printf "%s\n" "$latest_version" "$current_version" | sort -V | head -n1)" = "$current_version" ] && [ "$latest_version" != "$current_version" ]; then
            echo "::error::Version number in package.json ($current_version) must be greater than the latest release version ($latest_version)."
            exit 1
          fi

      - name: Check if changelog includes current version
        id: check_changelog
        run: |
          if ! grep -q "# v${{ env.current_version }}" changelog.md; then
            echo "::error::Changelog does not include the current version (${current_version})."
            exit 1
          fi
